---
# Display facts from all hosts and store them indexed by I(hostname) at C(/tmp/facts).

- name: Disable SElinux
  selinux: state=disabled

- name: stop and disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: repos.yml

- name: Install the Entermedia packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items: entermedia_pkgs
  when: ansible_os_family == 'RedHat'

- name: Install the Entermedia packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes
  with_items: entermedia_pkgs
  environment: env
  when: ansible_os_family == 'Debian'

- name: cp -rp qt-faststart /usr/bin
  copy: src=misc/qt-faststart dest=/usr/bin/qt-faststart

#- name: ln -s /usr/bin/avprobe /usr/bin/ffprobe
#  file: src=/usr/bin/avprobe dest=/usr/bin/ffprobe owner=root group=root state=link

- name: Add groups
  group: name={{ item }} state=present
  with_items:
    - entermedia
    - vboxsf

  # Add the user 'entermedia' with a bash shell, appending the group 'entermedia' and 'vboxsf' to the user's groups
- name: add user - entermedia
  user: name=entermedia shell=/bin/bash groups=entermedia,vboxsf append=yes

## Not needed for XFS
## Fix File Limits
#echo "fs.file-max = 10000000" >> /etc/sysctl.conf
#echo "entermedia      soft    nofile  409600" >> /etc/security/limits.conf
#echo "entermedia      hard    nofile  1024000" >> /etc/security/limits.conf
#sysctl -p
##End Fix File Limits

- name: mkdir /home/entermedia/.ffmpeg
  file: path=/home/entermedia/.ffmpeg state=directory owner=entermedia group=entermedia mode=0644

- name: cp .ffmpeg/libx264-normal.ffpreset /home/entermedia/.ffmpeg/libx264-normal.ffpreset
  copy: src=misc/.ffmpeg/libx264-normal.ffpreset dest=/home/entermedia/.ffmpeg/libx264-normal.ffpreset owner=entermedia group=entermedia

- name: rm ROOT.war - Previous version of EM
  file: path=/usr/share/tomcat/webapps/ROOT.war state=absent

- name: start service tomcat start
  service: name=tomcat state=started enabled=yes

- name: cp -p ../misc/delegates.xml /etc/ImageMagick/delegates.xml
  copy: src=etc/ImageMagick-6/delegates.xml dest=/etc/ImageMagick-6/delegates.xml owner=root group=root mode=0644

- name: cp tomcat-users.xml /etc/tomcat/
  copy: src=etc/tomcat/tomcat-users.xml dest=/etc/tomcat/tomcat-users.xml owner=tomcat group=tomcat mode=0660

- name: Check to see if there is an old ROOT folder in Tomcat
  stat: path=/var/lib/tomcat/webapps/ROOT
  register: ROOT_stat

- name: Move ROOT to ROOT-old
  command: mv /var/lib/tomcat/webapps/ROOT /var/lib/tomcat/webapps/ROOT-old
  when: ROOT_stat.stat.exists

- name: download Entermedia and install
  get_url: url=http://dev.entermediasoftware.com/jenkins/view/Demo/job/demoall/lastSuccessfulBuild/artifact/deploy/ROOT.war dest=/usr/share/tomcat/webapps/ROOT.war timeout=3600

- name: restart service tomcat restart
  service: name=tomcat state=restarted

#- name: add log location for manager application
#  template:
#    src: usr/share/tomcat/webapps/ROOT/WEB-INF/base/manager/catalog/data/lists/catalogsettings/base.xml.j2
#    dest: /var/lib/tomcat/webapps/ROOT/WEB-INF/base/manager/catalog/data/lists/catalogsettings/base.xml
#    owner: tomcat
#    group: tomcat
#    mode: 0644
#    backup: yes
#    force: yes

#- name: add log location for entermedia application
#  template:
#    src: usr/share/tomcat/webapps/ROOT/WEB-INF/base/entermedia/catalog/data/lists/catalogsettings/base.xml.j2
#    dest: /var/lib/tomcat/webapps/ROOT/WEB-INF/base/entermedia/catalog/data/lists/catalogsettings/base.xml
#    owner: tomcat
#    group: tomcat
#    mode: 0644
#    backup: yes
#    force: yes

#
#- name: create media directory
#  file: path=/media state=directory

##Copy data directory out and link it
#mkdir /media
#mv /opt/entermedia/webapp/WEB-INF/data /media
#ln -s /media/data /opt/entermedia/webapp/WEB-INF/data
#
#chown -R entermedia:entermedia /opt/entermedia
#
#chmod -R u+s,g+s /opt/entermedia
#
#cp
##iptables -F
#export ip=`ifconfig eth0 |grep "inet addr" |awk '{print $2}' |awk -F: '{print $2}'`
#/sbin/iptables -t nat -A OUTPUT -d localhost -p tcp --dport 80 -j REDIRECT --to-ports 8080
#/sbin/iptables -t nat -A OUTPUT -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
#/sbin/iptables -t nat -A PREROUTING -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
#
#/sbin/iptables -t nat -A OUTPUT -d localhost -p tcp --dport 22 -j REDIRECT --to-ports 22
#/sbin/iptables -t nat -A OUTPUT -d $ip -p tcp --dport 22 -j REDIRECT --to-ports 22
#/sbin/iptables -t nat -A PREROUTING -d $ip -p tcp --dport 22 -j REDIRECT --to-ports 22
#
#
#iptables-save > /etc/sysconfig/iptables



