---
  # ipv4

  # the following is used for when condition specified via firewall_type is avaialable
  # this would be whenever the firewall role is called via dep or role directly
- name: update firewall
  assemble: src=/etc/sysconfig/iptables.d dest=/etc/sysconfig/iptables delimiter='\n'
  when: firewall_type == "iptables-flattened"
  notify: reload iptables

  # the following is used for when condition specified via firewall_type is not avaialable
  # this happens in the teiid-side datasource setup for new world
- name: update iptables firewall
  assemble: src=/etc/sysconfig/iptables.d dest=/etc/sysconfig/iptables delimiter='\n'
  notify: reload iptables

- name: reload iptables
  service: name=iptables state=restarted

  # ipv6
  #
- name: update ipv6 firewall
  assemble: src=/etc/sysconfig/ip6tables.d dest=/etc/sysconfig/ip6tables delimiter='\n'
  when: firewall_type == "iptables-flattened"
  notify: reload ip6tables

- name: update ip6tables firewall
  assemble: src=/etc/sysconfig/ip6tables.d dest=/etc/sysconfig/ip6tables delimiter='\n'
  notify: reload ip6tables

- name: reload ip6tables
  service: name=ip6tables state=restarted
