---
    # if someone has not specified a firewall type directly then set the default based on distro version
  - set_fact: firewall_type=firewalld
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7" and firewall_type is not defined

  - set_fact: firewall_type=iptables-flattened
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6" and firewall_type is not defined

  - include: flattened.yml
    when: firewall_type == "iptables-flattened"
